receivers:
  otlp:
    protocols:
      grpc:
      http:
    
processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 2000
  batch:
  
exporters:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  otlp:
    endpoint: "es-cluster-fleet-server-1:8200"
    tls:
      insecure: true
    headers:
      Authorization: "Bearer supersecrettoken"
      compression: none
  prometheus:
    endpoint: "0.0.0.0:8889"
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors : [batch]
      exporters: [otlp, otlp/jaeger]
    metrics:
      receivers: [otlp]
      processors : [batch]
      exporters: [otlp, prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]